from typing import Literal
import warnings
import tyro
import os
import torch
import cv2
import imageio # To generate gifs
import pycolmap_scene_manager as pycolmap
from gsplat import rasterization
from ultralytics import YOLOWorld
from sam2.build_sam import build_sam2_video_predictor
import numpy as np
import time

def torch_to_cv(tensor):
    img_cv = tensor.detach().cpu().numpy()[..., ::-1]
    img_cv = np.clip(img_cv*255, 0, 255).astype(np.uint8)
    return img_cv

def _start_cv_feedback(window_name: str, feedback: bool) -> bool:
    if not feedback:
        return False
    try:
        cv2.destroyAllWindows()
        cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
        return True
    except cv2.error as exc:
        print(f"OpenCV visual feedback disabled: {exc}")
        return False

def _stop_cv_feedback(feedback: bool):
    if not feedback:
        return
    try:
        cv2.destroyAllWindows()
    except cv2.error:
        pass


def _detach_tensors_from_dict(d, inplace=True):
    if not inplace:
        d = d.copy()
    for key in d:
        if isinstance(d[key], torch.Tensor):
            d[key] = d[key].detach()
    return d


def load_checkpoint(checkpoint: str, data_dir: str, rasterizer: Literal["original", "inria", "gsplat"]="original", data_factor: int = 1):

    colmap_project = pycolmap.SceneManager(f"{data_dir}/sparse/0")
    colmap_project.load_cameras()
    colmap_project.load_images()
    colmap_project.load_points3D()
    model = torch.load(checkpoint, weights_only=False) # Make sure it is generated by 3DGS original repo
    is_inria_like = isinstance(model, (tuple, list))
    is_gsplat_like = isinstance(model, dict) and "splats" in model

    if rasterizer == "gsplat" and is_inria_like and not is_gsplat_like:
        warnings.warn(
            "Checkpoint appears to be INRIA/original-style (tuple). "
            "Overriding rasterizer='gsplat' -> 'original'.",
            RuntimeWarning,
        )
        rasterizer = "original"
    elif rasterizer in ("original", "inria") and is_gsplat_like and not is_inria_like:
        warnings.warn(
            "Checkpoint appears to be gsplat-style (dict with 'splats'). "
            f"Overriding rasterizer='{rasterizer}' -> 'gsplat'.",
            RuntimeWarning,
        )
        rasterizer = "gsplat"

    if rasterizer == "original" or rasterizer == "inria":
        model_params, _ = model
        splats = {
            "active_sh_degree": model_params[0],
            "means": model_params[1],
            "features_dc": model_params[2],
            "features_rest": model_params[3],
            "scaling": model_params[4],
            "rotation": model_params[5],
            "opacity": model_params[6].squeeze(1),
        }
    elif rasterizer == "gsplat":
        model_params = model["splats"]
        splats = {
            "active_sh_degree": 3,
            "means": model_params["means"],
            "features_dc": model_params["sh0"],
            "features_rest": model_params["shN"],
            "scaling": model_params["scales"],
            "rotation": model_params["quats"],
            "opacity": model_params["opacities"],
        }
    else:
        raise ValueError("Invalid rasterizer")

    _detach_tensors_from_dict(splats)

    # Assuming only one camera
    for camera in colmap_project.cameras.values():
        camera_matrix = torch.tensor(
            [
                [camera.fx, 0, camera.cx],
                [0, camera.fy, camera.cy],
                [0, 0, 1],
            ]
        )
        break

    camera_matrix[:2,:3] /= data_factor

    splats["camera_matrix"] = camera_matrix
    splats["colmap_project"] = colmap_project
    splats["colmap_dir"] = data_dir

    return splats

def get_viewmat_from_colmap_image(image):
    viewmat = torch.eye(4).float()#.to(device)
    viewmat[:3, :3] = torch.tensor(image.R()).float()#.to(device)
    viewmat[:3, 3] = torch.tensor(image.t).float()#.to(device)
    return viewmat

def create_checkerboard(width, height, size=64):
    checkerboard = np.zeros((height, width, 3), dtype=np.uint8)
    for y in range(0, height, size):
        for x in range(0, width, size):
            if (x // size + y // size) % 2 == 0:
                checkerboard[y:y + size, x:x + size] = 255
            else:
                checkerboard[y:y + size, x:x + size] = 128
    return checkerboard

def dilate_mask(mask, pixels: int):
    if pixels <= 0:
        return mask
    kernel_size = 2 * pixels + 1
    kernel = np.ones((kernel_size, kernel_size), dtype=np.uint8)
    return cv2.dilate(mask.astype(np.uint8), kernel, iterations=1).astype(bool)


def keep_largest_voxel_components(
    means,
    object_mask,
    voxel_size: float = 0.025,
    connectivity: Literal[6, 26] = 26,
    min_component_keep_ratio: float = 0.05,
):
    """Remove spatially scattered false positives from a 3D object mask."""
    object_indices = torch.where(object_mask)[0]
    if object_indices.numel() == 0:
        return object_mask, torch.zeros_like(object_mask), 0

    points = means[object_indices]
    min_point = torch.min(points, dim=0).values
    voxels = torch.floor((points - min_point) / voxel_size).long()
    unique_voxels, inverse = torch.unique(voxels, dim=0, return_inverse=True)

    voxel_list = [tuple(v) for v in unique_voxels.detach().cpu().tolist()]
    voxel_set = set(voxel_list)
    if connectivity == 6:
        offsets = [
            (1, 0, 0), (-1, 0, 0),
            (0, 1, 0), (0, -1, 0),
            (0, 0, 1), (0, 0, -1),
        ]
    elif connectivity == 26:
        offsets = [
            (dx, dy, dz)
            for dx in (-1, 0, 1)
            for dy in (-1, 0, 1)
            for dz in (-1, 0, 1)
            if not (dx == 0 and dy == 0 and dz == 0)
        ]
    else:
        raise ValueError("component_connectivity must be 6 or 26")

    voxel_to_component = {}
    component_count = 0
    for voxel in voxel_list:
        if voxel in voxel_to_component:
            continue
        stack = [voxel]
        voxel_to_component[voxel] = component_count
        while stack:
            current = stack.pop()
            for offset in offsets:
                neighbor = (
                    current[0] + offset[0],
                    current[1] + offset[1],
                    current[2] + offset[2],
                )
                if neighbor in voxel_set and neighbor not in voxel_to_component:
                    voxel_to_component[neighbor] = component_count
                    stack.append(neighbor)
        component_count += 1

    component_ids = torch.tensor(
        [voxel_to_component[voxel] for voxel in voxel_list],
        device=means.device,
        dtype=torch.long,
    )
    gaussian_component_ids = component_ids[inverse]
    component_sizes = torch.bincount(gaussian_component_ids, minlength=component_count)
    largest_component_size = torch.max(component_sizes)
    keep_components = component_sizes >= largest_component_size * min_component_keep_ratio

    cleaned_mask = torch.zeros_like(object_mask)
    kept_indices = object_indices[keep_components[gaussian_component_ids]]
    cleaned_mask[kept_indices] = True
    removed_mask = object_mask & ~cleaned_mask
    return cleaned_mask, removed_mask, component_count

def render_to_dir(output_dir: str, splats, feedback: bool = False):
    feedback = _start_cv_feedback("Initial Rendering", feedback)
    os.makedirs(output_dir, exist_ok=True)
    colmap_project = splats["colmap_project"]
    frame_idx = 0
    for image in sorted(colmap_project.images.values(), key=lambda x: x.name):
        image_name = image.name#.split(".")[0] + ".jpg"
        image_path = f"{output_dir}/{image_name}"
        means = splats["means"]
        colors_dc = splats["features_dc"]
        colors_rest = splats["features_rest"]
        colors = torch.cat([colors_dc, colors_rest], dim=1)
        opacities = torch.sigmoid(splats["opacity"])
        scales = torch.exp(splats["scaling"])
        quats = splats["rotation"]
        viewmat = get_viewmat_from_colmap_image(image)
        K = splats["camera_matrix"]
        output, _, info = rasterization(
            means,
            quats,
            scales,
            opacities,
            colors,
            viewmats=viewmat[None],
            Ks=K[None],
            sh_degree=3,
            width=K[0, 2] * 2,
            height=K[1, 2] * 2,
        )
        output_cv = torch_to_cv(output[0])
        imageio.imsave(image_path, output_cv[:, :, ::-1])
        if feedback:
            cv2.imshow("Initial Rendering", output_cv)
            cv2.waitKey(1)
        frame_idx += 1

def prune_by_gradients(splats):
    colmap_project = splats["colmap_project"]
    frame_idx = 0
    means = splats["means"]
    colors_dc = splats["features_dc"]
    colors_rest = splats["features_rest"]
    colors = torch.cat([colors_dc, colors_rest], dim=1)
    opacities = torch.sigmoid(splats["opacity"])
    scales = torch.exp(splats["scaling"])
    quats = splats["rotation"]
    K = splats["camera_matrix"]
    colors.requires_grad = True
    gaussian_grads = torch.zeros(colors.shape[0], device=colors.device)
    for image in sorted(colmap_project.images.values(), key=lambda x: x.name):
        viewmat = get_viewmat_from_colmap_image(image)
        output, _, _ = rasterization(
            means,
            quats,
            scales,
            opacities,
            colors[:,0,:],
            viewmats=viewmat[None],
            Ks=K[None],
            # sh_degree=3,
            width=K[0, 2] * 2,
            height=K[1, 2] * 2,
        )
        frame_idx += 1
        # pseudo_loss = ((output.detach() + 1 - output)**2).mean()
        pseudo_loss = output.mean()
        pseudo_loss.backward()
        # print(colors.grad.shape)
        gaussian_grads += (colors.grad[:,0]).norm(dim=[1])
        colors.grad.zero_()

    mask = gaussian_grads > 0
    print("Total splats", len(gaussian_grads))
    print("Pruned", (~mask).sum(), "splats")
    print("Remaining", mask.sum(), "splats")
    splats = splats.copy()
    splats["means"] = splats["means"][mask]
    splats["features_dc"] = splats["features_dc"][mask]
    splats["features_rest"] = splats["features_rest"][mask]
    splats["scaling"] = splats["scaling"][mask]
    splats["rotation"] = splats["rotation"][mask]
    splats["opacity"] = splats["opacity"][mask]
    return splats, mask

def test_proper_pruning(splats, splats_after_pruning):
    colmap_project = splats["colmap_project"]
    frame_idx = 0
    means = splats["means"]
    colors_dc = splats["features_dc"]
    colors_rest = splats["features_rest"]
    colors = torch.cat([colors_dc, colors_rest], dim=1)
    opacities = torch.sigmoid(splats["opacity"])
    scales = torch.exp(splats["scaling"])
    quats = splats["rotation"]

    means_pruned = splats_after_pruning["means"]
    colors_dc_pruned = splats_after_pruning["features_dc"]
    colors_rest_pruned = splats_after_pruning["features_rest"]
    colors_pruned = torch.cat([colors_dc_pruned, colors_rest_pruned], dim=1)
    opacities_pruned = torch.sigmoid(splats_after_pruning["opacity"])
    scales_pruned = torch.exp(splats_after_pruning["scaling"])
    quats_pruned = splats_after_pruning["rotation"]



    K = splats["camera_matrix"]
    total_error = 0
    max_pixel_error = 0
    for image in sorted(colmap_project.images.values(), key=lambda x: x.name):
        viewmat = get_viewmat_from_colmap_image(image)
        output, _, _ = rasterization(
            means,
            quats,
            scales,
            opacities,
            colors,
            viewmats=viewmat[None],
            Ks=K[None],
            sh_degree=3,
            width=K[0, 2] * 2,
            height=K[1, 2] * 2,
        )

        output_pruned, _, _ = rasterization(
            means_pruned,
            quats_pruned,
            scales_pruned,
            opacities_pruned,
            colors_pruned,
            viewmats=viewmat[None],
            Ks=K[None],
            sh_degree=3,
            width=K[0, 2] * 2,
            height=K[1, 2] * 2,
        )

        total_error += torch.abs((output - output_pruned)).sum()
        max_pixel_error = max(max_pixel_error, torch.abs((output - output_pruned)).max())

    percentage_pruned = (len(splats["means"]) - len(splats_after_pruning["means"])) / len(splats["means"]) * 100

    assert max_pixel_error < 1 / (255*2), "Max pixel error should be less than 1/(255*2), safety margin"
    print("Report {}% pruned, max pixel error = {}, total pixel error = {}".format(percentage_pruned, max_pixel_error, total_error))


def get_mask3d(
    splats,
    prompt,
    results_dir: str,
    show_visual_feedback: bool = True,
    mask_interval: int = 1,
    voting_method: Literal["gradient", "binary", "projection"] = "gradient",
    positive_mask_threshold: float = 0.0,
    negative_mask_threshold: float = -0.8,
    positive_vote_threshold: float = 0.0,
    negative_vote_threshold: float = 0.0,
    foreground_score_threshold: float = 0.55,
    background_score_threshold: float = 0.02,
    positive_mask_dilation: int = 0,
    background_exclusion_dilation: int = 32,
    positive_negative_vote_ratio: float = 1.0,
    remove_scattered_components: bool = True,
    component_voxel_size: float = 0.025,
    component_connectivity: Literal[6, 26] = 26,
    min_component_keep_ratio: float = 0.05,
):
    if negative_mask_threshold > positive_mask_threshold:
        raise ValueError(
            "negative_mask_threshold must be <= positive_mask_threshold. "
            "These thresholds are SAM logits, not probabilities; try positive=0.2 and negative=-0.2."
        )

    checkpoint = "./checkpoints/sam2_hiera_large.pt"
    if not os.path.exists(checkpoint):
        raise RuntimeError("Please download the checkpoint sam2_hiera_large.pt to checkpoints folder")
    
    if show_visual_feedback:
        show_visual_feedback = _start_cv_feedback("2D Mask", show_visual_feedback)
    model_cfg = "sam2_hiera_l.yaml"
    mask_predictor = build_sam2_video_predictor(model_cfg, checkpoint)
    yolo_world = YOLOWorld("yolov8s-worldv2.pt")
    torch.set_default_device("cpu")
    try:
        yolo_world.set_classes([prompt])
    finally:
        torch.set_default_device("cuda")
    colmap_project = splats["colmap_project"]
    first_image_name = sorted(colmap_project.images.values(), key=lambda x: x.name)[0].name
    first_image_path = f"{results_dir}/images/{first_image_name}"
    with torch.autocast("cuda", dtype=torch.bfloat16):
        state = mask_predictor.init_state(f"{results_dir}/images/")

        # Try a few variations if the specific prompt fails
        prompts_to_try = [prompt, "bottle", "plastic bottle", "container"]
        box = None
        
        for p in prompts_to_try:
            torch.set_default_device("cpu")
            try:
                yolo_world.set_classes([p])
            finally:
                torch.set_default_device("cuda")
                
            result = yolo_world(first_image_path, conf=0.1)[0] # Lower confidence for detection
            if len(result.boxes) > 0:
                print(f"Detected object using prompt: {p}")
                box = result.boxes[0].xyxy[0].tolist()
                break
        
        if box is None:
             raise RuntimeError(f"YOLOWorld could not find '{prompt}' in {first_image_path}. Please try a different prompt or check the image.")

        # add new prompts and instantly get the output on the same frame
        _, object_ids, masks = mask_predictor.add_new_points_or_box(
            state, box=box, frame_idx=0, obj_id=0
        )

        means = splats["means"]
        colors_dc = splats["features_dc"]

        colors = colors_dc[:,0,:] * 0 # Just to show that gradient (opacity * transmittance) is independent of color. Any value will work.


        opacities = torch.sigmoid(splats["opacity"])
        scales = torch.exp(splats["scaling"])
        quats = splats["rotation"]
        K = splats["camera_matrix"]
        colors.requires_grad = True

        positive_votes = torch.zeros(colors.shape[0], device=colors.device)
        negative_votes = torch.zeros(colors.shape[0], device=colors.device)
        print(
            "Mask thresholds: "
            f"positive logits >= {positive_mask_threshold}, "
            f"background logits <= {negative_mask_threshold}, "
            f"voting={voting_method}, "
            f"foreground_score >= {foreground_score_threshold}, "
            f"positive/background ratio >= {positive_negative_vote_ratio}"
        )
        print(
            "Mask morphology: "
            f"positive dilation={positive_mask_dilation}px, "
            f"background exclusion dilation={background_exclusion_dilation}px"
        )

        mask_dir = f"{results_dir}/masks_with_images"
        mask_bin_dir = f"{results_dir}/masks_bin"
        background_bin_dir = f"{results_dir}/background_masks_bin"
        debug_mask_dir = f"{results_dir}/mask_debug_overlays"
        os.makedirs(mask_dir, exist_ok=True)
        os.makedirs(mask_bin_dir, exist_ok=True)
        os.makedirs(background_bin_dir, exist_ok=True)
        os.makedirs(debug_mask_dir, exist_ok=True)
        
        # propagate the prompts to get masklets throughout the video
        frame_idx = 0
        voted_frame_count = 0
        positive_pixel_fractions = []
        background_pixel_fractions = []
        ambiguous_pixel_fractions = []
        for image, (frame_idx, object_ids, masks) in zip(
            sorted(colmap_project.images.values(), key=lambda x: x.name),
            mask_predictor.propagate_in_video(state),
        ):

            image_name = image.name#.split(".")[0] + ".jpg"
            # image_name = f"frame_"
            image_path = f"{results_dir}/images/{image_name}"
            mask_path = f"{mask_dir}/{image_name}"
            mask_bin_path = f"{mask_bin_dir}/{image.name}"

            frame = cv2.imread(image_path)
            mask_logits = masks[0, 0].cpu().numpy().astype(np.float32)
            mask_logits = cv2.blur(mask_logits, (7, 7))
            positive_seed_mask = mask_logits >= positive_mask_threshold
            positive_mask = dilate_mask(positive_seed_mask, positive_mask_dilation)
            background_mask = mask_logits <= negative_mask_threshold
            background_mask &= ~dilate_mask(positive_seed_mask, background_exclusion_dilation)
            ambiguous_mask = ~(positive_mask | background_mask)
            mask = positive_mask

            positive_pixel_fractions.append(float(positive_mask.mean()))
            background_pixel_fractions.append(float(background_mask.mean()))
            ambiguous_pixel_fractions.append(float(ambiguous_mask.mean()))

            mask_red = np.zeros_like(frame)

            mask_red[:, :, -1][mask] = 255
            mask_bin = mask.astype(np.uint8) * 255
            background_bin = background_mask.astype(np.uint8) * 255
            debug_overlay = frame.copy()
            debug_overlay[background_mask] = (
                debug_overlay[background_mask].astype(np.float32) * 0.5
                + np.array([255, 0, 0], dtype=np.float32) * 0.5
            ).astype(np.uint8)
            debug_overlay[positive_mask] = (
                debug_overlay[positive_mask].astype(np.float32) * 0.5
                + np.array([0, 0, 255], dtype=np.float32) * 0.5
            ).astype(np.uint8)
            debug_overlay[ambiguous_mask] = (
                debug_overlay[ambiguous_mask].astype(np.float32) * 0.5
                + np.array([0, 255, 255], dtype=np.float32) * 0.5
            ).astype(np.uint8)
            cv2.imwrite(mask_bin_path, mask_bin)
            cv2.imwrite(f"{background_bin_dir}/{image.name}", background_bin)
            cv2.imwrite(f"{debug_mask_dir}/{image.name}", debug_overlay)
            output = cv2.addWeighted(frame, 1, mask_red, 0.5, 0)
            cv2.imwrite(mask_path, output)


            frame_idx += 1
            if (frame_idx % mask_interval != 1) and (mask_interval != 1):
                continue
            if show_visual_feedback:
                cv2.imshow("2D Mask", output)
                cv2.waitKey(1)
            voted_frame_count += 1
            
            viewmat = get_viewmat_from_colmap_image(image)

            
            width = frame.shape[1]
            height = frame.shape[0]

            output_for_grad, _, meta = rasterization(
                means,
                quats,
                scales,
                opacities,
                colors,
                viewmat[None],
                K[None],
                width=width,
                height=height,
                # sh_degree=3,
            )

            target = output_for_grad[0] * torch.from_numpy(positive_mask)[..., None].cuda().float()
            loss = 1 * target.mean()

            loss.backward(retain_graph=True)
            if voting_method == "gradient":
                mins = torch.min(colors.grad, dim=-1).values
                maxes = torch.max(colors.grad, dim=-1).values
                assert torch.allclose(mins , maxes), "Something is wrong with gradient calculation"
                positive_votes += (colors.grad).norm(dim=[1])
            elif voting_method == "binary":
                positive_votes += 1 * (colors.grad.norm(dim=[1]) > 0)
            elif voting_method == "projection":

                means2d = np.round(meta["means2d"].detach().cpu().numpy()).astype(int)
                means2d_mask = (means2d[:, 0] >= 0) & (means2d[:, 0] < width) & (means2d[:, 1] >= 0) & (means2d[:, 1] < height)
                means2d = means2d[means2d_mask]
                gaussian_ids = meta["gaussian_ids"].detach().cpu().numpy()
                gaussian_ids = gaussian_ids[means2d_mask]

                positive_projected = positive_mask[means2d[:, 1], means2d[:, 0]]
                background_projected = background_mask[means2d[:, 1], means2d[:, 0]]
                gaussian_ids_t = torch.from_numpy(gaussian_ids).long().to(colors.device)
                positive_projected_t = torch.from_numpy(positive_projected).bool().to(colors.device)
                background_projected_t = torch.from_numpy(background_projected).bool().to(colors.device)
                ones = torch.ones_like(gaussian_ids_t, dtype=positive_votes.dtype)
                positive_votes.index_add_(0, gaussian_ids_t[positive_projected_t], ones[positive_projected_t])
                negative_votes.index_add_(0, gaussian_ids_t[background_projected_t], ones[background_projected_t])
            else:
                raise ValueError("Invalid voting method")

            colors.grad.zero_()

            target = output_for_grad[0] * torch.from_numpy(background_mask).cuda()[
                ..., None
            ]
            loss = 1 * target.mean()
            loss.backward(retain_graph=False)

            if voting_method == "gradient":
                negative_votes += (colors.grad).norm(dim=[1])
            elif voting_method == "binary":
                negative_votes += 1 * ((colors.grad).norm(dim=[1]) > 0)
            elif voting_method == "projection":
                pass
            else:
                raise ValueError("Invalid voting method")
            colors.grad.zero_()

        vote_total = positive_votes + negative_votes
        foreground_score = positive_votes / vote_total.clamp_min(1e-8)
        has_positive_votes = positive_votes > positive_vote_threshold
        has_negative_votes = negative_votes > negative_vote_threshold
        positive_beats_background = positive_votes > (negative_votes * positive_negative_vote_ratio)
        mask_3d_raw = has_positive_votes & positive_beats_background & (foreground_score >= foreground_score_threshold)
        mask_3d = mask_3d_raw
        removed_components = torch.zeros_like(mask_3d)
        component_count = 0
        if remove_scattered_components:
            mask_3d, removed_components, component_count = keep_largest_voxel_components(
                means,
                mask_3d,
                voxel_size=component_voxel_size,
                connectivity=component_connectivity,
                min_component_keep_ratio=min_component_keep_ratio,
            )
        confident_background = has_negative_votes & (foreground_score <= background_score_threshold)
        mask_3d_inverted = ~mask_3d
        ambiguous_votes = has_positive_votes & has_negative_votes
        if positive_pixel_fractions:
            print(
                "2D vote masks: "
                f"foreground mean={np.mean(positive_pixel_fractions) * 100:.3f}%, "
                f"background mean={np.mean(background_pixel_fractions) * 100:.3f}%, "
                f"ignored/ambiguous mean={np.mean(ambiguous_pixel_fractions) * 100:.3f}%"
            )
        foreground_scores_with_votes = foreground_score[vote_total > 0]
        if len(foreground_scores_with_votes) > 0:
            qs = torch.quantile(
                foreground_scores_with_votes,
                torch.tensor([0.5, 0.9, 0.99], device=foreground_score.device),
            )
            print(
                "3D foreground-score quantiles for visible Gaussians: "
                f"p50={qs[0].item():.4f}, p90={qs[1].item():.4f}, p99={qs[2].item():.4f}"
            )
        print(f"Frames used for 3D voting: {voted_frame_count}")
        print(f"Gaussians above positive vote threshold: {int(has_positive_votes.sum().item())}")
        print(f"Gaussians above negative vote threshold: {int(has_negative_votes.sum().item())}")
        print(f"Gaussians with both positive and negative votes: {int(ambiguous_votes.sum().item())}")
        print(f"Gaussians where positive votes beat background votes: {int(positive_beats_background.sum().item())}")
        print(f"Gaussians confidently background-like: {int(confident_background.sum().item())}")
        print(f"3D mask Gaussians before component cleanup: {int(mask_3d_raw.sum().item())}")
        if remove_scattered_components:
            print(f"3D mask voxel components found: {component_count}")
            print(f"Scattered component Gaussians moved to background: {int(removed_components.sum().item())}")
        print(f"3D mask Gaussians selected: {int(mask_3d.sum().item())}")
        torch.save(
            {
                "positive_votes": positive_votes.detach().cpu(),
                "negative_votes": negative_votes.detach().cpu(),
                "foreground_score": foreground_score.detach().cpu(),
                "mask_3d_raw": mask_3d_raw.detach().cpu(),
                "mask_3d": mask_3d.detach().cpu(),
                "removed_components": removed_components.detach().cpu(),
                "foreground_score_threshold": foreground_score_threshold,
                "positive_negative_vote_ratio": positive_negative_vote_ratio,
                "positive_mask_threshold": positive_mask_threshold,
                "negative_mask_threshold": negative_mask_threshold,
                "positive_mask_dilation": positive_mask_dilation,
                "background_exclusion_dilation": background_exclusion_dilation,
                "remove_scattered_components": remove_scattered_components,
                "component_voxel_size": component_voxel_size,
                "component_connectivity": component_connectivity,
                "min_component_keep_ratio": min_component_keep_ratio,
            },
            f"{results_dir}/vote_stats.pth",
        )
        return mask_3d, mask_3d_inverted

def apply_mask3d(splats, mask3d,mask3d_inverted, results_dir: str):
    if mask3d_inverted == None:
        mask3d_inverted = ~mask3d
    print(f"Applying 3D mask: extracting {int(mask3d.sum().item())} Gaussians")
    if int(mask3d.sum().item()) == 0:
        print("Warning: extracted mask is empty; extracted_images will be empty.")
    extracted = splats.copy()
    deleted = splats.copy()
    masked = splats.copy()
    extracted["means"] = extracted["means"][mask3d]
    extracted["features_dc"] = extracted["features_dc"][mask3d]
    extracted["features_rest"] = extracted["features_rest"][mask3d]
    extracted["scaling"] = extracted["scaling"][mask3d]
    extracted["rotation"] = extracted["rotation"][mask3d]
    extracted["opacity"] = extracted["opacity"][mask3d]

    deleted["means"] = deleted["means"][mask3d_inverted]
    deleted["features_dc"] = deleted["features_dc"][mask3d_inverted]
    deleted["features_rest"] = deleted["features_rest"][mask3d_inverted]
    deleted["scaling"] = deleted["scaling"][mask3d_inverted]
    deleted["rotation"] = deleted["rotation"][mask3d_inverted]
    deleted["opacity"] = deleted["opacity"][mask3d_inverted]

    masked["features_dc"][mask3d] = 1#(1 - 0.5) / 0.2820947917738781
    masked["features_dc"][~mask3d] = 0#(0 - 0.5) / 0.2820947917738781
    masked["features_rest"][~mask3d] = 0

    return extracted, deleted, masked

    

def render_to_gif(output_path: str, splats, feedback: bool = False, use_checkerboard_background: bool = False, no_sh: bool=False):
    feedback = _start_cv_feedback("Rendering", feedback)
    frames = []
    means = splats["means"]
    colors_dc = splats["features_dc"]
    colors_rest = splats["features_rest"]
    colors = torch.cat([colors_dc, colors_rest], dim=1)
    if no_sh == True:
        colors = colors_dc[:,0,:]
    opacities = torch.sigmoid(splats["opacity"])
    scales = torch.exp(splats["scaling"])
    quats = splats["rotation"]
    K = splats["camera_matrix"]
    aux_dir = output_path + ".images"
    os.makedirs(aux_dir, exist_ok=True)
    for image in sorted(splats["colmap_project"].images.values(), key=lambda x: x.name):
        viewmat = get_viewmat_from_colmap_image(image)
        output, alphas, meta = rasterization(
            means,
            quats,
            scales,
            opacities,
            colors,
            viewmat[None],
            K[None],
            width=K[0, 2]*2,
            height=K[1, 2]*2,
            sh_degree=3 if not no_sh else None,
        )
        frame = np.clip(output[0].detach().cpu().numpy() * 255, 0, 255).astype(np.uint8)
        if use_checkerboard_background:
            checkerboard = create_checkerboard(frame.shape[1], frame.shape[0])
            alphas = alphas[0].detach().cpu().numpy()
            frame = frame * alphas + checkerboard * (1 - alphas)
            frame = np.clip(frame, 0, 255).astype(np.uint8)
        frames.append(frame)
        if feedback:
            cv2.imshow("Rendering", frame[...,::-1])
            cv2.imwrite(f"{aux_dir}/{image.name}", frame[...,::-1])
            cv2.waitKey(1)
    imageio.mimsave(output_path, frames, fps=10)
    _stop_cv_feedback(feedback)
def render_segmented_to_dir(output_dir: str, splats, feedback: bool = False, use_checkerboard_background: bool = False):
    feedback = _start_cv_feedback("Segmented Rendering", feedback)
    os.makedirs(output_dir, exist_ok=True)
    means = splats["means"]
    colors_dc = splats["features_dc"]
    colors_rest = splats["features_rest"]
    colors = torch.cat([colors_dc, colors_rest], dim=1)
    opacities = torch.sigmoid(splats["opacity"])
    scales = torch.exp(splats["scaling"])
    quats = splats["rotation"]
    K = splats["camera_matrix"]
    
    for image in sorted(splats["colmap_project"].images.values(), key=lambda x: x.name):
        viewmat = get_viewmat_from_colmap_image(image)
        output, alphas, meta = rasterization(
            means,
            quats,
            scales,
            opacities,
            colors,
            viewmat[None],
            K[None],
            width=K[0, 2]*2,
            height=K[1, 2]*2,
            sh_degree=3,
        )
        frame = np.clip(output[0].detach().cpu().numpy() * 255, 0, 255).astype(np.uint8)
        if use_checkerboard_background:
            checkerboard = create_checkerboard(frame.shape[1], frame.shape[0])
            alphas_np = alphas[0].detach().cpu().numpy()
            frame = frame * alphas_np + checkerboard * (1 - alphas_np)
            frame = np.clip(frame, 0, 255).astype(np.uint8)
        
        image_path = f"{output_dir}/{image.name}"
        cv2.imwrite(image_path, frame[..., ::-1])
        
        if feedback:
            cv2.imshow("Segmented Rendering", frame[...,::-1])
            cv2.waitKey(1)
    _stop_cv_feedback(feedback)
def render_mask_pred(output_dir: str, splats, feedback: bool = False):
    feedback = _start_cv_feedback("Rendering", feedback)
    frames = []
    means = splats["means"]
    colors_dc = splats["features_dc"]
    colors_rest = splats["features_rest"]

    colors = colors_dc[:,0,:]
    opacities = torch.sigmoid(splats["opacity"])
    scales = torch.exp(splats["scaling"])
    quats = splats["rotation"]
    K = splats["camera_matrix"]
    aux_dir = output_dir
    os.makedirs(aux_dir, exist_ok=True)
    for image in sorted(splats["colmap_project"].images.values(), key=lambda x: x.name):
        viewmat = get_viewmat_from_colmap_image(image)
        output, alphas, meta = rasterization(
            means,
            quats,
            scales,
            opacities,
            colors,
            viewmat[None],
            K[None],
            width=K[0, 2]*2,
            height=K[1, 2]*2,
            sh_degree=None,
        )
        frame = np.clip(output[0].detach().cpu().numpy() * 255, 0, 255).astype(np.uint8)
        frame = frame > 128
        frame = frame.astype(np.uint8) * 255
            # cv2.imshow("Checkerboard", checkerboard)
        # frames.append(frame)
        if feedback:
            cv2.imshow("Rendering", frame[...,::-1])
            cv2.imwrite(f"{aux_dir}/{image.name}", frame)
            cv2.waitKey(1)
    # imageio.mimsave(output_path, frames, fps=10)
    _stop_cv_feedback(feedback)

def export_mask(mask3d, prune_mask, results_dir: str):
    if prune_mask is not None:
        mask3d_export = torch.zeros_like(prune_mask).bool()
        mask3d_export[prune_mask] = mask3d
        torch.save(mask3d_export, f"{results_dir}/mask3d.pth")
    else:
        torch.save(mask3d, f"{results_dir}/mask3d.pth")

def main(
        data_dir: str = "./data/person", # colmap path
        checkpoint: str = "./data/person/chkpnt30000.pth", # checkpoint path, can generate from original 3DGS repo
        prompt: str = "person", # prompt
        results_dir: str = "./results/person", # output path
        show_visual_feedback: bool = True, # Will show opencv window,
        rasterizer: Literal["original", "inria", "gsplat"] = "original", # Original/INRIA or GSplat checkpoints
        data_factor: int = 1,
        mask_interval: int = 1,
        voting_method: Literal["gradient", "binary", "projection"] = "gradient",
        positive_mask_threshold: float = 0.0,
        negative_mask_threshold: float = -0.8,
        positive_vote_threshold: float = 0.0,
        negative_vote_threshold: float = 0.0,
        foreground_score_threshold: float = 0.55,
        background_score_threshold: float = 0.02,
        positive_mask_dilation: int = 0,
        background_exclusion_dilation: int = 32,
        positive_negative_vote_ratio: float = 1.0,
        remove_scattered_components: bool = True,
        component_voxel_size: float = 0.025,
        component_connectivity: Literal[6, 26] = 26,
        min_component_keep_ratio: float = 0.05,
):
    """
    Demo program.


    Args:
        data_dir: Path to the colmap project directory
        checkpoint: Path to the checkpoint file
        prompt: Prompt for the mask prediction
        results_dir: Path to the output directory
        show_visual_feedback: Show visual feedback
        rasterizer: Rasterizer/checkpoint format. Use original or inria for INRIA 3DGS checkpoints, gsplat for gsplat checkpoints.
        data_factor: Factor to scale down the resolution of the images
        mask_interval: The interval between images for taking masked gradients
        voting_method: Voting method to generate 3D mask
        positive_mask_threshold: SAM mask-logit threshold for positive object votes
        negative_mask_threshold: SAM mask-logit threshold for negative background votes
        positive_vote_threshold: Minimum accumulated positive vote needed to extract a Gaussian
        negative_vote_threshold: Minimum accumulated negative vote used for background confidence reporting
        foreground_score_threshold: Minimum positive / (positive + negative) support needed to extract a Gaussian
        background_score_threshold: Positive support below this value is counted as confidently background-like for reporting
        positive_mask_dilation: Pixel dilation applied to the positive 2D mask before 3D voting
        background_exclusion_dilation: Pixels around the original positive mask ignored for background voting
        positive_negative_vote_ratio: Positive votes must exceed this multiple of background votes
        remove_scattered_components: Remove disconnected 3D mask components after voting
        component_voxel_size: Voxel size in meters for 3D connected-component cleanup
        component_connectivity: Voxel connectivity used for component cleanup
        min_component_keep_ratio: Keep components at least this large relative to the largest component
    """
    
    if not torch.cuda.is_available():
        raise RuntimeError("CUDA is required for this demo")
    if negative_mask_threshold > positive_mask_threshold:
        raise ValueError(
            "negative_mask_threshold must be <= positive_mask_threshold. "
            "These thresholds are SAM logits, not probabilities; try positive=0.2 and negative=-0.2."
        )
    
    start_total = time.time()
    torch.set_default_device('cuda')

    os.makedirs(results_dir, exist_ok=True)
    
    start_load = time.time()
    splats = load_checkpoint(checkpoint, data_dir, rasterizer=rasterizer, data_factor=data_factor)
    end_load = time.time()
    print(f"Checkpoint loading took: {end_load - start_load:.2f}s")

    start_prune = time.time()
    splats_optimized, prune_mask = prune_by_gradients(splats)
    test_proper_pruning(splats, splats_optimized)
    end_prune = time.time()
    print(f"Pruning took: {end_prune - start_prune:.2f}s")

    del splats
    splats = splats_optimized

    start_render_dir = time.time()
    render_to_dir(f"{results_dir}/images", splats, show_visual_feedback)
    end_render_dir = time.time()
    print(f"Rendering images to dir took: {end_render_dir - start_render_dir:.2f}s")

    start_mask = time.time()
    mask3d, mask3d_inverted = get_mask3d(
        splats,
        prompt,
        results_dir,
        show_visual_feedback,
        mask_interval=mask_interval,
        voting_method=voting_method,
        positive_mask_threshold=positive_mask_threshold,
        negative_mask_threshold=negative_mask_threshold,
        positive_vote_threshold=positive_vote_threshold,
        negative_vote_threshold=negative_vote_threshold,
        foreground_score_threshold=foreground_score_threshold,
        background_score_threshold=background_score_threshold,
        positive_mask_dilation=positive_mask_dilation,
        background_exclusion_dilation=background_exclusion_dilation,
        positive_negative_vote_ratio=positive_negative_vote_ratio,
        remove_scattered_components=remove_scattered_components,
        component_voxel_size=component_voxel_size,
        component_connectivity=component_connectivity,
        min_component_keep_ratio=min_component_keep_ratio,
    )
    end_mask = time.time()
    print(f"3D Mask generation took: {end_mask - start_mask:.2f}s")
    
    export_mask(mask3d, prune_mask, results_dir)
    
    start_apply = time.time()
    extracted, deleted, masked = apply_mask3d(splats, mask3d, mask3d_inverted, results_dir)
    end_apply = time.time()
    print(f"Applying 3D mask took: {end_apply - start_apply:.2f}s")

    start_render_ext = time.time()
    print("Rendering extracted images...")
    render_segmented_to_dir(f"{results_dir}/extracted_images", extracted, show_visual_feedback, use_checkerboard_background=True)
    end_render_ext = time.time()
    print(f"Rendering extracted images took: {end_render_ext - start_render_ext:.2f}s")

    start_render_del = time.time()
    print("Rendering deleted images...")
    render_segmented_to_dir(f"{results_dir}/deleted_images", deleted, show_visual_feedback, use_checkerboard_background=False)
    end_render_del = time.time()
    print(f"Rendering deleted images took: {end_render_del - start_render_del:.2f}s")
    
    # render_mask_pred(f"{results_dir}/mask_bin_pred", masked, show_visual_feedback)
    # render_to_gif(f"{results_dir}/extracted.gif", extracted, show_visual_feedback, use_checkerboard_background=True)
    # render_to_gif(f"{results_dir}/deleted.gif", deleted, show_visual_feedback)
    # render_to_gif(f"{results_dir}/masked.gif", masked, show_visual_feedback, no_sh=True)
    
    end_total = time.time()
    print("-" * 30)
    print(f"Total processing time: {end_total - start_total:.2f}s")
    print("-" * 30)


if __name__ == "__main__":
    tyro.cli(main)
